apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
    name: resultapp-service
    app: voting-app
spec:
  selector:
    name: result-app-pod
    app: voting-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  