apiVersion: v1
kind: Service
metadata:
  name: votingapp-service
  labels:
    name: votingapp-service
    app: voting-app
spec:
  selector:
    name: voting-app-pod
    app: voting-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004